[affils]
uoft = "Department of Computer Science, University of Toronto, Canada"
[[author]]
givenName = "Zi-Jian"
familyName = "Zhang"
affil = ["uoft","EvoEvolver Institude, Canada"]
note = "email"
[authorNotes]
email = "zijian.academic@outlook.com"