projectTitle = "Evomark"
linearize = ["index", "grammar-markdown", "grammar-evomark", "open-source-future", "meta-info", "credit-system","how-design","paper-like-example"]
chatUrl = "https://gitter.im/evoreview/community"
gitRepoUrl = "https://github.com/EvoEvolver/evomark-framework/tree/main/docs_src"