projectTitle = "Evomark"
linearize = ["index", "install", "grammar-markdown", "grammar-evomark", "slides","open-source-future", "meta-info", "credit-system","how-design","white-paper"]
chatUrl = "https://gitter.im/EvoEvolver/community"
gitRepoUrl = "https://github.com/EvoEvolver/evomark-framework/tree/main/docs_src"
[license]
title = "Creative Commons Attribution-ShareAlike 4.0 International License"
link = "https://creativecommons.org/licenses/by-sa/4.0/"
[affils]
uoft = "Department of Computer Science, University of Toronto, Canada"
[[author]]
givenName = "Zi-Jian"
familyName = "Zhang"
affil = ["uoft"]
note = "email"
[authorNotes]
email = "zijian.academic@outlook.com"

[[responsibleAuthor]]
name = "Zi-Jian Zhang"
link = "https://github.com/doomspec"